// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvZkQhsMSBq-VkRUEzH4HSfFt-e__ros',
    appId: '1:986954985396:web:43608a4c5f1475126e0ce1',
    messagingSenderId: '986954985396',
    projectId: 'forja-ff92b',
    authDomain: 'forja-ff92b.firebaseapp.com',
    storageBucket: 'forja-ff92b.appspot.com',
    measurementId: 'G-P8P5BQFSJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsWkCDODPYEjAdrNWgQGEaqsPsX0-AWs',
    appId: '1:986954985396:android:b13e3c7643571a686e0ce1',
    messagingSenderId: '986954985396',
    projectId: 'forja-ff92b',
    storageBucket: 'forja-ff92b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjddrMAx7a-MLJy1_5BFl0pqrnJODcnA4',
    appId: '1:986954985396:ios:b4e8b91fd347fdb86e0ce1',
    messagingSenderId: '986954985396',
    projectId: 'forja-ff92b',
    storageBucket: 'forja-ff92b.appspot.com',
    iosBundleId: 'com.example.forja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjddrMAx7a-MLJy1_5BFl0pqrnJODcnA4',
    appId: '1:986954985396:ios:b4e8b91fd347fdb86e0ce1',
    messagingSenderId: '986954985396',
    projectId: 'forja-ff92b',
    storageBucket: 'forja-ff92b.appspot.com',
    iosBundleId: 'com.example.forja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgvZkQhsMSBq-VkRUEzH4HSfFt-e__ros',
    appId: '1:986954985396:web:bd8db149d5e586cf6e0ce1',
    messagingSenderId: '986954985396',
    projectId: 'forja-ff92b',
    authDomain: 'forja-ff92b.firebaseapp.com',
    storageBucket: 'forja-ff92b.appspot.com',
    measurementId: 'G-78PLW98VCC',
  );
}
